### ISSUE TITLE
sample vs. motif signatures

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/BAGEL#10]
Right now we use the term "signature" to refer both to the probability of a motif in a signature and the proportion of that signature in a tumor. It would be useful to have two different naming conventions similar to terms vs. topics. Previously Alexandrov et al used "Exposures" to refer to the signature proportions in tumors.

**Comment by achevali** [comment]
Exposures? Processes? 

Consider new terms that reflect both the math and biology if possible and are less ambiguous/vague.

**Comment by achevali** [comment]
Using exposures and signatures for now, will reopen if I have a better naming convention in mind
