### ISSUE TITLE
Decouple reading in maf/vcf and feature table creation

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/BAGEL#11]
Users may want to further filter their maf/vcf using custom criteria (or not filter their vcf at all). Rather than parsing the file and then converting directly to the feature data table, our functions should just convert a VariantAnnotation object or maf object into the feature data table. Let the user deal with any manipulations before hand.

**Comment by achevali** [comment]
Create new functions for read a user filtered maf/vcf from the packages that load them into a Bagel-style data.table.
