### ISSUE TITLE
More flexibility in feature data table structure

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/BAGEL#12]
Multiple types of mutation will be present (e.g. SNV, DNP, indel, SV, etc). Each type of mutation will have its own set of additional features. For example, SNVs may have flanking base and strand, while indels can have size, in repeat, within region of microhomology. The structure of the feature tables needs to be flexible 

One suggestion is to have an S4 object which is just a list of data tables (one data.table for each feature type).

**Comment by achevali** [comment]
Create slots and functions for count schemas for indels and flanking to load into prototype expanded model.
