### ISSUE TITLE
add_variant_type improvments

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/BAGEL#43]
Does not seem sufficient. Assumes NAs are indels? Why would there be an NA? Should probably exclude NAs.

Does not currently label DBS/DNP or ONPs. 

Does not identify SVs. 

Does not distinguish between INS/DEL. they need to be labeled differently

Look at VariantAnnotation methods that identify type (isSNV, isDEL, etc) for guides and to validate that our function works properly

**Comment by achevali** [comment]
Fixed in previous release
