### ISSUE TITLE
Vignette improvements

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/BAGEL#46]
1) Needs to conform to bioconductor standards:

https://www.bioconductor.org/developers/package-guidelines/#documentation

Including sections for Introduction, Installation, etc.

2) Also, it should be named something simple (i.e. bagel) so it is easy to remember when calling the vignette function: vignettes("bagel")

3) Shouldn't start all function calls with "BAGEL::". This is not necessary from the user's perspective. Analysts shouldn't need to care about namespaces, but developers sure do! Same goes for all the documentation.

4) Need better sections with paragraphs. Need to describe the steps to give the user some context as to what is going on. See decontX or scruff vignettes for examples. For example, in importing variant section, you can show one example, but then mention all the other functions and what they import in the paragraph.

**Comment by achevali** [comment]
Added all except renaming the vignette to "bagel"
