### ISSUE TITLE
compare_cosmic

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/BAGEL#52]
This warning appears once every time when running cosmic_compare_v2. It needs to be fixed. 

`Warning message:
The `.data` argument of `add_column()` must have unique names as of tibble 3.0.0.
Use `.name_repair = "minimal"`.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. `

**Comment by achevali** [comment]
Should be fixed, reopen if it re-occurs
