### ISSUE TITLE
plot_sample/plot_samples improvements

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/BAGEL#6]
1) Need ability to turn off sample labels
2) proportion=FALSE does not work
3) get rid of grid, should use classical theme from ggplots
4) The two functions plot_sample and plot_samples have almost identical names although they plot different things (sample counts vs. signature counts in samples). They need distinct and more informative names

**Comment by joshua-d-campbell** [comment]
5) Need the ability to sort samples in various ways including total number of mutations or mutations of specific signature. 
6) Need the ability to plot the top X number of samples (e.g. 20). Combined with number 5, this will allow for plot observed in publications
7) Also the ability to plot a user-defined list of samples

**Comment by achevali** [comment]
2. Multiply weights by sample counts in lda discovery and prediction functions
